-- CREATE DATABASE Practicas;
-- USE Practicas;
-- CREATE TABLE Users (id INT PRIMARY KEY IDENTITY(1,1), name VARCHAR(255) NOT NULL, email VARCHAR(255) NOT NULL, password VARCHAR(255) NOT NULL, age INT, birthdate DATE);
-- INSERT INTO Users (name, email, password, age, birthdate) VALUES ('David','d@d.com','ddd',21,'2002-03-06');
-- SELECT * FROM Users;
-- INSERT INTO Users (name, email, password, age, birthdate) VALUES ('Oscar','o@o.com','ooo',21,'2002-02-05'),('Eduardo','e@e.com','eee',21,'2002-04-07'),('Roberto','r@r.com','rrr',21,'2002-06-09');